### ISSUE TITLE
[1.0] Feature Checklist

### ISSUE THREAD

**Issue by jlengstorf** [gramps-graphql/gramps-cli#12]
Let's get this thing to 1.0!

For the CLI, here's what we need to do:

- [x] Design: Finalize the API #9 
- [x] Refactor: Start data source(s) with a local dev server (this should already work, but needs to be refactored to the formate in #9) #11 
- [x] Feature: Add support for using a custom gateway during local dev #10 
- [x] Docs: Write CLI docs #6 
- [x] Docs: Update the README #13 

~~- [ ] Feature: Move to Typescript~~ #8 <-- let's do this, but not block the 1.0 release for it.

@ecwyne @corycook Am I missing anything here?

**Comment by jlengstorf** [comment]
We're live! https://www.npmjs.com/package/@gramps/cli
